# Generated by Django 6.0.5 on 2026-05-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_generation_provider', models.CharField(default='openai', max_length=50)),
                ('text_generation_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('text_generation_base_url', models.CharField(default='https://api.openai.com/v1', max_length=255)),
                ('text_generation_model_name', models.CharField(default='gpt-4o', max_length=100)),
                ('text_generation_temperature', models.FloatField(default=0.7)),
                ('embedding_provider', models.CharField(default='openai', max_length=50)),
                ('embedding_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding_base_url', models.CharField(default='https://api.openai.com/v1', max_length=255)),
                ('embedding_model_name', models.CharField(default='text-embedding-3-large', max_length=100)),
                ('embedding_dimension', models.IntegerField(default=1024)),
                ('rerank_provider', models.CharField(default='cohere', max_length=50)),
                ('rerank_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('rerank_base_url', models.CharField(default='https://api.cohere.com/v1', max_length=255)),
                ('rerank_model_name', models.CharField(default='rerank-english-v3.0', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
