# Generated by Django 6.0.5 on 2026-05-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfig',
            name='embedding_input_type',
            field=models.CharField(choices=[('query', 'query'), ('document', 'document')], default='query', max_length=20),
        ),
    ]
