# Generated by Django
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('md5_hash', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='MD5哈希')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(max_length=50, verbose_name='文件类型')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME类型')),
                ('storage_type', models.CharField(choices=[('original', '原始文件'), ('converted', '转换文件'), ('attachment', '附件'), ('chunk', '文档片段'), ('embedding', '向量嵌入'), ('thumbnail', '缩略图')], max_length=20, verbose_name='存储类型')),
                ('relative_path', models.CharField(max_length=500, verbose_name='相对路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='documents.document', verbose_name='关联文档')),
            ],
            options={
                'db_table': 'file_storage',
                'verbose_name': '文件存储',
                'verbose_name_plural': '文件存储',
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('position', models.IntegerField(default=0, verbose_name='排序位置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.document', verbose_name='所属文档')),
                ('file_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.filestorage', verbose_name='存储文件')),
            ],
            options={
                'db_table': 'file_attachment',
                'verbose_name': '文档附件',
                'verbose_name_plural': '文档附件',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentConversion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待转换'), ('converting', '转换中'), ('success', '转换成功'), ('failed', '转换失败')], default='pending', max_length=20, verbose_name='转换状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('conversion_info', models.JSONField(default=dict, verbose_name='转换信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('converted_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_conversions', to='documents.filestorage', verbose_name='转换后文件')),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='documents.filestorage', verbose_name='原始文件')),
            ],
            options={
                'db_table': 'document_conversion',
                'verbose_name': '文档转换记录',
                'verbose_name_plural': '文档转换记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
