# Generated by Django 6.0.5 on 2026-05-13 05:08

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('directory', 'name'), name='unique_directory_name'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'name'), name='unique_parent_name'),
        ),
    ]
