# Generated by Django 6.0.5 on 2026-05-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentchunk_embedding_vector_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('folder__isnull', True)), fields=('directory', 'filename'), name='unique_directory_filename'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('folder__isnull', False)), fields=('folder', 'filename'), name='unique_folder_filename'),
        ),
    ]
