# Generated by Django 6.0.5 on 2026-05-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_unique_directory_filename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='directory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folder',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
