# Generated by Django 6.0.5 on 2026-05-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_directory_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
