# Generated by Django 6.0.5 on 2026-05-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='openclaw_api_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='openclaw_session_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
