# Generated by Django 6.0.5 on 2026-05-14 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_openclaw_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='openclaw_api_key',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='openclaw_session_key',
        ),
    ]
